In [119]:
# Importação das bibliotecas necessárias
import pandas as pd
import numpy as np
import matplotlib as plt

# Definição do caminho dos dados
caminho_dados = "BaseVarejoDadosBrutos.csv"

In [120]:
# Leitura dos dados com a utilização dos parâmetros abaixo:
# dtype - para que as colunas que devem ser do tipo string, não sejam lidas como do tipo inteiro
# parse_dates - para instruir o pandas a interpretar a coluna DATA como data/datetime
# na_values - para definir que o valor "#N/D" seja tratado como valor ausente (NaN).
# keep_default_na=True - para que além de "#N/D", outros valores padrão, reconhecidos como ausentes, também sejam convertidos para NaN
df = pd.read_csv(caminho_dados, sep= ";", dtype= {"CO_ID": "string", 
                                                  "CL_ID": "string", 
                                                  "PR_ID": "string"},
                                                  parse_dates=["DATA"],na_values=["#N/D"], keep_default_na=True)

In [121]:
df.columns

Index(['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG',
       'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13'],
      dtype='object')

In [122]:
# Exibição das primeiras linhas do dataframe
df.head(3)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN

In [123]:
# Verificação do tamanho do conjunto de dados
print("total de linhas:", df.shape[0])
print("total de colunas:", df.shape[1])

total de linhas: 830000
total de colunas: 14

In [124]:
# Inspeção das colunas existentes, nulos e tipos dos dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  object
 1   CO_ID        830000 non-null  string
 2   CL_ID        830000 non-null  string
 3   CL_GENERO    830000 non-null  object
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  object
 7   PR_ID        830000 non-null  string
 8   PR_CAT       826350 non-null  object
 9   PR_NOME      826350 non-null  object
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(2), object(5), string(3)
memory usage: 88.7+ MB


### Dicionário de dados

1. DATA: Data da compra;  
2. CO_ID: Identificação do número de compra (número da nota fiscal);  
3. CL_ID: Identificação do cliente (número do cliente);  
4. CL_GENERO: Sexo biológico informado pelo cliente;  
5. CL_EC: Estado civil do cliente:  1: Casado ou união estával; 2: Divorciado; 3: Separado;  4: Solteiro;  5: Viúvo.  
6. CL_FHL: Número de filhos do cliente;  
7. CL_SEG: Segmentação econômica do cliente (classe A, B ou C);  
8. PR_ID: Código do produto (SKU) adquirido;  
9. PR_CAT: Categoria do produto adquirido;  
10. PR_NOME: Nome do produto adquirido.

In [125]:
# Conversão do tipo da coluna DATA de string para datetime
print("Tipo da coluna DATA antes da transformação:" , df["DATA"].dtype)
df["DATA"] = pd.to_datetime(df["DATA"], format = "%d/%m/%Y")
print("Tipo da coluna DATA após a transformação:" , df["DATA"].dtype)

Tipo da coluna DATA antes da transformação: object
Tipo da coluna DATA após a transformação: datetime64[ns]

In [126]:
# Lista com os nomes das colunas
print("Nome das colunas:" , df.columns.tolist())

Nome das colunas: ['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

In [127]:
# Identificação da data inicial e final do registro dos dados
print("Período compreendido entre:")
print(df["DATA"].min().strftime("%d/%m/%Y"), "e", df["DATA"].max().strftime("%d/%m/%Y"))

Período compreendido entre:
04/01/2019 e 08/12/2022

In [128]:
# Verificação de presença de nulos
print("Total de nulos por coluna:")
print(df.isnull().sum())

Total de nulos por coluna:
DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT           3650
PR_NOME          3650
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

In [129]:
# Percentual de nulos
print(df.isnull().mean()*100)

DATA             0.000000
CO_ID            0.000000
CL_ID            0.000000
CL_GENERO        0.000000
CL_EC            0.000000
CL_FHL           0.000000
CL_SEG           0.000000
PR_ID            0.000000
PR_CAT           0.439759
PR_NOME          0.439759
Unnamed: 10    100.000000
Unnamed: 11    100.000000
Unnamed: 12    100.000000
Unnamed: 13    100.000000
dtype: float64

In [130]:
# Seleção das colunas válidas
df = df[['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']]

In [131]:
# Tratamento das variáveis categóricas com dados inconsistentes

In [133]:
len(df)

830000

In [134]:
# Tratamento das células nulas em PR_CAT e PR_NOME, tendo por base a coluna PR_ID

# Antes é necessário excluir os valores que estão simultaneamente nulos em PR_CAT e PR_NOME,mantendo somente os valores válidos, 
# ou seja, não nulos nas 3 colunas de interesse
validos = df.dropna(subset=["PR_CAT", "PR_NOME"])


# Verificar se um mesmo PR_ID não está associado a mais de um valor diferente de PR_CAT ou de PR_NOME 
#Para cada PR_ID, contamos quantos valores distintos existem em PR_CAT e em PR_NOME. Se um ID tem sempre a mesma categoria e o mesmo nome, 
# o resultado será 1 em ambas as colunas — o esperado.
conflitos = (validos.groupby("PR_ID")[["PR_CAT", "PR_NOME"]].nunique().query("PR_CAT >1 or PR_NOME > 1"))
print(f"IDs com conflito: {len(conflitos)}")
conflitos.head()

IDs com conflito: 0

Empty DataFrame
Columns: [PR_CAT, PR_NOME]
Index: []

In [135]:
# Construção da tabela com os dados referentes aos ids, caegorias e nomes dos produtos, que servirá de referência para o tratamento dos nulos em PR_CAT e PR_NOME
tabela_ref_produtos = (validos
               .drop_duplicates("PR_ID")[["PR_ID", "PR_CAT", "PR_NOME"]]
               .set_index("PR_ID"))

tabela_ref_produtos.head()

          PR_CAT               PR_NOME
PR_ID
67       BEBIDAS  REFRIGERANTE GUARANA
70       BEBIDAS   REFRIGERANTE OUTROS
178      HIGIENE       LENCO UMEDECIDO
4      ALIMENTOS               ABACAXI
175      LIMPEZA     LIMPADOR MULTIUSO

In [136]:
print("Contagem do total de ids de produtos referenciados na tabela")
print(len(tabela_ref_produtos))

print("Contagem do total ids de produtos identificados na tabela de venda")
print(df["PR_ID"].nunique())

Contagem do total de ids de produtos referenciados na tabela
228
Contagem do total ids de produtos identificados na tabela de venda
229

In [137]:
# Contagem dos nulos antes do preenchimento
nulos_antes = df[["PR_CAT", "PR_NOME"]].isnull().sum()
print("Total de nulos antes do preenchimento:")
print(nulos_antes)

Total de nulos antes do preenchimento:
PR_CAT     3650
PR_NOME    3650
dtype: int64

In [138]:
# Identificar ids produtos que não tem correspondencia na tabela de referencia para preencher nulos como "Não informado"

df["PR_CAT"]  = (df["PR_CAT"]
                 .fillna(df["PR_ID"].map(tabela_ref_produtos["PR_CAT"]))
                 .fillna("Não informado"))

df["PR_NOME"] = (df["PR_NOME"]
                 .fillna(df["PR_ID"].map(tabela_ref_produtos["PR_NOME"]))
                 .fillna("Não informado"))

In [139]:
# Contagem dos nulos após o preenchimento
nulos_apos = df[["PR_CAT", "PR_NOME"]].isnull().sum()
print("Total de nulos após o preenchimento:")
print(nulos_apos)

Total de nulos após o preenchimento:
PR_CAT     0
PR_NOME    0
dtype: int64

In [ ]:
# Tratamento dos dados das variáveis categóricas

In [140]:
# Identificação de duplicados
print('Número de linhas do dataframe antes da exclusão dos duplicados:', df.shape[0])
print("Total de duplicados exatos encontrados:", df.duplicated().sum())

# Visualizar os duplicados
duplicados = df[df.duplicated()]
duplicados.head(10)

Número de linhas do dataframe antes da exclusão dos duplicados: 830000
Total de duplicados exatos encontrados: 96553

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
19,2019-02-01,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
40,2019-02-01,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
46,2019-02-01,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE
49,2019-02-01,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO
50,2019-02-01,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE
51,2019-02-01,1000,534,M,4,1,C,225,ALIMENTOS,ATUM
77,2019-02-01,1078,290,F,1,0,B,210,ACESSORIOS,CHUPETA
78,2019-02-01,1078,290,F,1,0,B,99,LIMPEZA,DESINFETANTE
96,2019-02-01,1078,290,F,1,0,B,144,BEBIDAS,REFRIGERANTE COLA
97,2019-02-01,1078,290,F,1,0,B,125,HIGIENE,TINTURAS

In [ ]:
df.groupby

In [59]:
df['PR_NOME'].unique()

array(['REFRIGERANTE GUARANA', 'REFRIGERANTE OUTROS', 'LENCO UMEDECIDO',
       'ABACAXI', 'LIMPADOR MULTIUSO', 'HASTES FLEXIVEIS', 'MORTADELA',
       'AZEITE', 'AMACIANTE', 'ENERGETICO', 'LATA DE ERVILHA',
       'PRESERVATIVO', 'BANANA', 'DETERGENTE', 'BIFE DE COXAO MOLE',
       'PAPEL HIGIENICO', 'UVA', 'LIMPA VIDROS', 'RICOTA', 'REMOVEDOR',
       'REFRIGERANTE LIMaO', 'QUEIJO MUSSARELA', 'SARDINHA', 'FRALDA',
       'GRANOLA', 'RODO', 'ARROZ INTEGRAL', 'COGUMELOS', 'PATE',
       'PALMITO', 'ATUM', 'TIRA MANCHA', 'CORACAO DE FRANGO', 'ALMONDEGA',
       'SABONETE', 'COPA SUINA', 'KETCHUP', 'REFRIGERANTE COLA',
       'REFRIGERANTE LARANJA', 'REPELENTE', 'LEITE CONDENSADO', 'ALCOOL',
       'MORDEDOR', 'ESCOVA DE DENTE', 'RACAO UMIDA PARA GATOS', 'OVOS',
       'MAMAO PAPAYA', 'SABAO', 'CAFE', 'LUSTRA MOVEIS', 'CONDICIONADOR',
       'SALGADINHOS DE MILHO', 'LEITE', 'DESINFETANTE', 'CHUPETA',
       'FIXADOR', 'ALHO', 'TINTURAS', 'PASTA DE DENTE',
       'RACAO SECA PARA CAES', 'RACAO UMIDA PARA CAES', '#N/D',
       'HIDRATANTE', 'AGUA SANITARIA', 'SNACKS', 'BATATA', 'SHAMPOO',
       'LATA DE MILHO', 'SALGADINHO', 'QUEIJO DE CABRA', 'ODORIZADOR',
       'LINGUICA', 'REQUEIJAO', 'ACHOCOLATADO', 'BISCOITO', 'FIO DENTAL',
       'FILE DE PEIXE', 'PROTETOR SOLAR', 'GEL', 'MAMAO', 'CENOURA',
       'TOMATE', 'LIMPADOR PERFUMADO', 'CHA', 'LIMAO', 'PRESUNTO COZIDO',
       'SABAO EM PO', 'DANETTE', 'CERA', 'PAPINHA INFANTIL', 'TALCO',
       'TIRA LIMO', 'FEIJAO', 'MODELADOR', 'VASSOURA',
       'MACARRAO INSTANTANEO', 'DESENGORDURANTE', 'RACAO SECA PARA GATOS',
       'CREME', 'INSETICIDA', 'BATATA DOCE', 'DOCE', 'PAO DE FORMA',
       'MACARRAO', 'IOGURTE', 'BALDE', 'BROCOLIS', 'AZEITONA',
       'HAMBUGUER', 'ALIMENTO PARA PASSARO', 'CEBOLA', 'ENXAGUANTE BUCAL',
       'MANGA', 'COXA E SOBRECOXA DE FRANGO', 'ABACATE', 'ARROZ',
       'ABSORVENTE', 'MOLHO BARBECUE'], dtype=object)

In [19]:
df["PR_NOME"].nunique()

118

In [20]:
df["PR_ID"].nunique()

229

In [3]:
df.describe()

,CO_ID,CL_ID,CL_EC,CL_FHL,PR_ID,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
count,830000.000000,830000.000000,830000.000000,830000.00000,830000.000000,0.0,0.0,0.0,0.0
mean,460045.089890,499.595204,2.596911,1.14654,115.051855,NaN,NaN,NaN,NaN
std,265465.247541,287.568253,1.170599,1.41696,66.129241,NaN,NaN,NaN,NaN
min,1000.000000,1.000000,1.000000,0.00000,1.000000,NaN,NaN,NaN,NaN
25%,233117.000000,254.000000,2.000000,0.00000,58.000000,NaN,NaN,NaN,NaN
50%,456517.000000,498.000000,3.000000,0.00000,115.000000,NaN,NaN,NaN,NaN
75%,690132.000000,746.000000,4.000000,2.00000,172.000000,NaN,NaN,NaN,NaN
max,919822.000000,1000.000000,5.000000,4.00000,229.000000,NaN,NaN,NaN,NaN

In [18]:
df["PR_NOME"].nunique()

118

In [ ]:
colunas = ['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']

print(df.columns.tolist())




print(df[['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']].head())

print(df[['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']].tail())

print(df[['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']].describe())

df = df[["DATA","CL_ID","PR_NOME","PR_CAT","PR_ID","CL_GENERO"]]

print(df.size)